### ISSUE TITLE
next ssr problem

### ISSUE THREAD

**Issue by landsman** [kidjp85/react-id-swiper#300]
Hi, I have a problem with server side rendering with Next.js.

**Error:**
```
Unexpected token {
/home/landsman/projects/company/web/node_modules/swiper/dist/js/swiper.esm.js:13
import { $, addClass, removeClass, hasClass, toggleClass, attr, removeAttr, data, transform, transition as transition$1, on, off, trigger, transitionEnd as transitionEnd$1, outerWidth, outerHeight, offset, css, each, html, text, is, index, eq, append, prepend, next, nextAll, prev, prevAll, parent, parents, closest, find, children, remove, add, styles } from 'dom7/dist/dom7.modular';
       ^

SyntaxError: Unexpected token {
    at Module._compile (internal/modules/cjs/loader.js:721:23)
    at Object.Module._extensions..js (internal/modules/cjs/loader.js:787:10)
    at Module.load (internal/modules/cjs/loader.js:653:32)
    at tryModuleLoad (internal/modules/cjs/loader.js:593:12)
    at Function.Module._load (internal/modules/cjs/loader.js:585:3)
    at Module.require (internal/modules/cjs/loader.js:690:17)
    at require (internal/modules/cjs/helpers.js:25:18)
    at Object.<anonymous> (/home/landsman/projects/company/web/node_modules/react-id-swiper/lib/ReactIdSwiper.js:25:20)
    at Module._compile (internal/modules/cjs/loader.js:776:30)
    at Object.Module._extensions..js (internal/modules/cjs/loader.js:787:10)
    at Module.load (internal/modules/cjs/loader.js:653:32)
    at tryModuleLoad (internal/modules/cjs/loader.js:593:12)
    at Function.Module._load (internal/modules/cjs/loader.js:585:3)
    at Module.require (internal/modules/cjs/loader.js:690:17)
    at require (internal/modules/cjs/helpers.js:25:18)
    at Object.<anonymous> (/home/landsman/projects/company/web/node_modules/react-id-swiper/lib/index.js:6:39)
```

**Code:**
```
import React from "react";
import Swiper from 'react-id-swiper';
// Need to add Pagination, Navigation modules
import { Pagination, Navigation } from 'swiper/dist/js/swiper.esm'
import "../scss/drupal/embeds/carousel-core.scss";

export default class Carousel extends React.Component {
    constructor (props) {
        super(props);
    }

    componentDidMount(){

    }

    render () {
        const { children, hidePagination } = this.props;

        const params = {
            modules: [Pagination, Navigation],
            pagination: {
                el: '.swiper-pagination',
                type: 'bullets',
                clickable: true
            },
            navigation: {
                nextEl: '.swiper-button-next',
                prevEl: '.swiper-button-prev'
            },
            spaceBetween: 30
        };

        if (hidePagination) {
            delete params.pagination;
        }

        return(
            <>
                <Swiper >
                    {children}
                </Swiper>
            </>
        )
    }
}
```

**Comment by selique** [comment]
same problem

**Comment by dusanstojanovic** [comment]
Same here

**Comment by jdmoliner** [comment]
same problem

**Comment by kidjp85** [comment]
You guy can find the discussion [here](https://github.com/kidjp85/react-id-swiper/issues/273)

**Comment by nghiepit** [comment]
`Next.js`  have problems with the new version `2.3.1`.
With `CRA`, `Next.js`... I think you need to create example repo for each of them.

**Comment by kidjp85** [comment]
@nghiepit , which problem are u facing ? Can u provide demo from codesanbox?

**Comment by nghiepit** [comment]
@jdmoliner I don't know, but I just upgraded from `2.1.2` to `2.3.1` and changed
`import Swiper from 'react-id-swiper/lib/ReactIdSwiper.full'` to `import Swiper from 'react-id-swiper'`
`npm run dev`  app loading long time and no response.

**Comment by kidjp85** [comment]
@nghiepit , please check CHANGELOG to see the diff. From version `2.3.0`, you can use default import like `import Swiper from 'react-id-swiper'`

**Comment by landsman** [comment]
@kidjp85 Why do you event used Dom7? It's really overkill for me. I have to switch to another lib :(

**Comment by kidjp85** [comment]
@landsman , it's from Swiper not from `react-id-swiper`

**Comment by fandy** [comment]
👍 same issue for me

**Comment by tohbansoon** [comment]
For my case, i use:

```
import { Swiper } from 'swiper/dist/js/swiper.esm.js'
import ReactIdSwiper from 'react-id-swiper/lib/ReactIdSwiper.custom'
```

I was unable to start the server again if using custom build.... I m using webpack.... 

but `import ReactIdSwiper from 'react-id-swiper'` is working fine

**Comment by oyilmaztekin** [comment]
I think I am missing something. The server-side rendering has been already accomplished on the official documentation website. https://react-id-swiper.ashernguyen.site/example/multiple-slides-per-view . It can be seen the next server drawing skeleton of the slider area and it is providing valid HTML for slide content at the beginning. Disabling js and refreshing the page doesn't affect the result. It is SSR then. I think it would be great to share your experience with server-side DOM creation @kidjp85.
