### ISSUE TITLE
Failed to execute 'remove' on 'DOMTokenList': The token provided must not be empty

### ISSUE THREAD

**Issue by BramDecuypere** [kidjp85/react-id-swiper#389]
On navigating between certain pages, I'm seeing this error popup. It looks like during cleanup, there is something going wrong with the swiper component?

```
Uncaught DOMException: Failed to execute 'remove' on 'DOMTokenList': The token provided must not be empty.
    at Dom7.removeClass (http://localhost:4000/_next/static/chunks/5.js:222:105)
    at Swiper.removeClasses (http://localhost:4000/_next/static/chunks/5.js:4606:7)
    at Swiper.destroy (http://localhost:4000/_next/static/chunks/5.js:5243:14)
    at destroySwiper (http://localhost:4000/_next/static/chunks/5.js:1520:39)
```

**Comment by LucasLeandroBR** [comment]
I've the same issue.

**Comment by Sense** [comment]
Same here, the error is raising when the `Swiper` is unmounted (my two cents ; `removeClass` on the `destroy` swiper function call may have be called on a null element). Any idea on this @kidjp85 please ? (seems like a common issue)

**Comment by kidjp85** [comment]
It should be fixed in the newest version.

**Comment by Nightliss** [comment]
```Uncaught DOMException: Failed to execute 'remove' on 'DOMTokenList': The token provided must not be empty.
    at Dom7.removeClass (http://localhost:3002/static/js/1.chunk.js:237:105)
    at Swiper.removeClasses (http://localhost:3002/static/js/1.chunk.js:5362:7)
    at Swiper.destroy (http://localhost:3002/static/js/1.chunk.js:5988:14)

**Comment by Nightliss** [comment]
```js
Uncaught DOMException: Failed to execute 'remove' on 'DOMTokenList': The token provided must not be empty.
    at Dom7.removeClass (http://localhost:3002/static/js/1.chunk.js:237:105)
    at Swiper.removeClasses (http://localhost:3002/static/js/1.chunk.js:5362:7)
    at Swiper.destroy (http://localhost:3002/static/js/1.chunk.js:5988:14)
```

```json
"react-id-swiper": "^4.0.0",
"swiper": "^5.4.5",
```

I'm having the same issue. Errors in dev and build envs. I seem to have latest versions of the react-id-swiper and swiper. Any ideas @kidjp85

**Comment by exsesx** [comment]
Any updates?

**Comment by BramDecuypere** [comment]
> Any updates?

@exsesx I've moved to swiper completely, since they have their own react implementation (for me this one became way less relevant)
